version: 2.1

jobs:
    lint:
        docker:
            - image: cimg/node:18.14.0
        steps:
            - checkout
            - restore_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
            - run:
                  name: Install dependencies
                  command: npm install
            - save_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
                  paths:
                      - ./node_modules
            - run:
                  name: Lint check
                  command: npm run lint

    build-and-deploy:
        docker:
            - image: cimg/node:18.14.0
        steps:
            - checkout
            - restore_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
            - run:
                  name: Install dependencies
                  command: npm install
            - save_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
                  paths:
                      - ./node_modules
            - setup_remote_docker:
                  version: 20.10.14
                  docker_layer_caching: true
            - run:
                  name: Login Dockerhub
                  command: |
                      echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            - run:
                  name: Build docker image
                  command: |
                      TAG=0.1.$CIRCLE_BUILD_NUM
                      docker build -t $DOCKER_USER/la-peche-fe:latest ./
                      docker build -t $DOCKER_USER/la-peche-fe:$TAG ./
            - run:
                  name: Check images
                  command: docker images
            - run:
                  name: Push images
                  command: |
                      TAG=0.1.$CIRCLE_BUILD_NUM
                      docker push $DOCKER_USER/la-peche-fe:latest
                      docker push $DOCKER_USER/la-peche-fe:$TAG
            - run:
                  name: Trigger deploy with Jenkins
                  command: |
                      curl -X POST $JENKINS_URL/generic-webhook-trigger/invoke?token=app-build -d '{"image_version": "0.1.$CIRCLE_BUILD_NUM"}' -H 'Content-Type: application/json'


workflows:
    ci-web:
        jobs:
            - lint
            - build-and-deploy:
                  requires:
                      - lint
                  filters:
                      branches:
                          only:
                              - main
                              - develop
